# https://jupyterbook.org/customize/config.html
title: "Hanghai Li's Portfolio"
author: Hanghai Li

# https://jupyterbook.org/en/stable/structure/configure.html#disable-building-files-that-are
only_build_toc_files: true
exclude_patterns:
  - .github/*
  - .pytest_cache/*
  - .venv/*

execute:
  execute_notebooks: "off"

sphinx:
  config:
    myst_heading_anchors: 4
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.7/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]


